// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSyItHHy7e27UnOtTEk08H01E94LkXkY',
    appId: '1:1073542511419:web:f9cda01f5958c4e838951e',
    messagingSenderId: '1073542511419',
    projectId: 'pontual-sempre',
    authDomain: 'pontual-sempre.firebaseapp.com',
    storageBucket: 'pontual-sempre.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZqU_1muCTfISZJNZe1IVEdfDUUOF7RQ',
    appId: '1:1073542511419:android:c0d5e58dfd55826438951e',
    messagingSenderId: '1073542511419',
    projectId: 'pontual-sempre',
    storageBucket: 'pontual-sempre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDFZ7g51_jN7UiqyHy8f-pNNMds5mQNo',
    appId: '1:1073542511419:ios:66afc981ba837b5b38951e',
    messagingSenderId: '1073542511419',
    projectId: 'pontual-sempre',
    storageBucket: 'pontual-sempre.firebasestorage.app',
    iosBundleId: 'com.salles.pontual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDFZ7g51_jN7UiqyHy8f-pNNMds5mQNo',
    appId: '1:1073542511419:ios:66afc981ba837b5b38951e',
    messagingSenderId: '1073542511419',
    projectId: 'pontual-sempre',
    storageBucket: 'pontual-sempre.firebasestorage.app',
    iosBundleId: 'com.salles.pontual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwSyItHHy7e27UnOtTEk08H01E94LkXkY',
    appId: '1:1073542511419:web:b235fbbefe06278338951e',
    messagingSenderId: '1073542511419',
    projectId: 'pontual-sempre',
    authDomain: 'pontual-sempre.firebaseapp.com',
    storageBucket: 'pontual-sempre.firebasestorage.app',
  );
}
